services:
    bambui:
        build: .
        ports:
            - 8080:8080
        command: uvicorn bambu.main:app --host 0.0.0.0 --port 8080 --reload
        volumes:
            - ./bambu:/app/bambu
